# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 327da92cd74d90f4a0d67019421553b3b2a8e3153c38f34c9e3b088f81899324d4f483241b15cdd73d85b8d38c498e1a36d5c17fdce17492d4eff0c0e165c27c

test:
  secret_key_base: 6d0e0c542792de172de9a67c2e03dbb8c6d441949998ee3cb3b71dab0eb8d20efc6b351d5e3a502c455a473673cb73e2f5be8b99b0de56ba62b687e7c96e5a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
